#!/bin/bash
#修改tomcat的日志级别为debug并重启
echo -n "请输入项目路径:"
read filePath
sed -i 's/INFO/DEBUG/g' ${filePath}/webapps/ROOT/WEB-INF/classes/logback.xml
sh ${filePath}/bin/shutdown.sh
sleep 3
pid=`ps -ef|grep tomcat |grep -w "$filePath "|grep -v 'grep'|awk '{print $2}'`
if [  $pid ];then
     echo "[$pid]进程将强制关闭"
  	kill -9 "$pid"
  	pid1=`ps -ef|grep tomcat |grep -w "$filePath "|grep -v 'grep'|awk '{print $2}'`
  	if [  $pid1 ];then
		echo '进程关闭失败,请手工重启!'
	else
          echo 'starting'
		sh ${filePath}/bin/startup.sh
	fi
else
     echo 'starting'
	sh ${filePath}/bin/startup.sh
fi
